
project_id = "pwknncursthenghqgevl"

[functions.send-weekly-reports]
verify_jwt = false

[functions.generate-lyrics]
verify_jwt = true

[auth.external.dropbox]
enabled = true
client_id = ""
secret = ""
